/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //gettingStartedSideBar: [{type: 'autogenerated', dirName: 'getting-started'}],
  iconsSideBar: [
    'icons/icon-sets',
    {
      type: 'category',
      label: 'Popular Icon Sets',
      link: {type: 'generated-index'},
      collapsed: false,
      items: [
        'icons/fluentui-system-icons',
        'icons/fluentui-emoji',
        'icons/google-material-design',
      ],
    },
  ],
  tech: [{type: 'autogenerated', dirName: 'technical-guide'}],
  // But you can create a sidebar manually
  userSideBar: [
    'user-guide/home-screen',
    {
      type: 'category',
      label: 'App Themes Workbench',
      link: {type: 'doc', id: 'user-guide/theme-workbench'},
      collapsed: false,
      items: [
        'user-guide/create-new-theme',
        'user-guide/load-a-theme',
        'user-guide/print-a-theme',
        'user-guide/export-a-theme',
      ],
    },
    {
      type: 'category',
      label: 'Color Workbench',
      link: {type: 'doc', id: 'user-guide/color-workbench'},
      collapsed: false,
      items: [
        'user-guide/color-contrast-checker',
        'user-guide/color-blindness-simulation',
        'user-guide/color-api',
        'user-guide/colorfyit-tab',

      ],
    },
    {
      type: 'category',
      label: 'Iconography Workbench',
      link: {type: 'doc', id: 'user-guide/iconography-workbench'},
      collapsed: false,
      items: [
        'user-guide/search-icons',
        
      ],
    },
    {
      type: 'doc',
      label: 'Font Workbench',
      id: 'user-guide/font-workbench',
    },
    {
      type: 'category',
      label: 'Icon Set Administration',
      link: {type: 'doc', id: 'user-guide/icon-set-administration'},
      collapsed: false,
      items: [
        'user-guide/icon-set-transforms',
        
      ],
    },
  ],
  gettingStartedSideBar: [
    'getting-started/introduction',
        {
          type: 'category',
          label: 'Installation',
          link: {type: 'doc', id: 'getting-started/Installation'},
          collapsed: false,
          items: [
            'getting-started/configure-dataflow',
            'getting-started/loading-icons',
            
          ],
        },
        'getting-started/create-a-theme'
      ],
  
};

module.exports = sidebars;
